### ISSUE TITLE
Error when using the module: Cannot find module './cli.config.json'

### ISSUE THREAD

**Issue by claudiu-carcadia** [danitseitlin/cli-argument-parser#20]
**Describe the bug**
If I define a configuration file named './cli.config.json' as it is written in the documentation, I get error when I'm trying to use the module:

```
Error: Cannot find module './cli.config.json'
    at loadArguments (/home/claudiu/Auto/New-BO/qa/ui/node_modules/cli-argument-parser/lib/index.js:13:51)
    at Object.<anonymous> (/home/claudiu/Auto/New-BO/qa/ui/node_modules/cli-argument-parser/lib/index.js:8:24)
    at Object.<anonymous> (/home/claudiu/Auto/New-BO/qa/ui/page-models/pm.base.ts:4:1)
    at Object.<anonymous> (/home/claudiu/Auto/New-BO/qa/ui/tests/test.contract.create.ts:1:1)
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**

**Additional context**

**Comment by danitseitlin** [comment]
@claudiu-carcadia This was already resolved in #18 so I closed this as duplicate.
In addition, there are so changes in the configuration contents so I recommend taking a peek in the README (https://github.com/danitseitlin/cli-argument-parser)
